### ISSUE TITLE
Importing into Unreal Engine difficulties

### ISSUE THREAD

**Issue by SijmenHuizenga** [BMEAutomatedDrive/ZalaZONE-automotive-proving-ground-virtual-simulation-models#1]
Amazing project you have here! We would love to give it a try :heart: 

We are using Unreal Engine 4 but we can't get the world to load. Unpackaging using 7zip succeeded and importing the fbx file also seemed to work. But when loading the map into the world we get the following. 

![image](https://user-images.githubusercontent.com/8008227/81084736-90c2b580-8ef6-11ea-8b91-63b6ef038f7a.png)

Would you be able to provide a small instruction on how to get this world loaded into UE4? Or maybe point me in the direction where we can learn how to do this?

**Comment by SijmenHuizenga** [comment]
After a tip from one of the creators (thanks!) I found this [page](https://tracetransit.atlassian.net/wiki/spaces/VS/pages/743800952/Exporting+to+Unreal) with a tutorial on how to import The trick is to select "FBX Scene Import" in the 'import' file selection window. This will show you a bunch of new options. The tutorial linked shows screenshots with recommended settings. Using those it works!

![Screenshot from 2020-05-20 11-25-48](https://user-images.githubusercontent.com/8008227/82430628-e3bb7180-9a8d-11ea-9720-e4ff0c03e86e.png)

**Comment by BMEAutomatedDrive** [comment]
You're welcome. :)

**Comment by Lu7913** [comment]
Hi,
@SijmenHuizenga How exactly did you unpack those files? I have unpacked 7zip archive, which results in a folder, not a fbx file. Is there some kind of process to get fbx file from those unpacked files?

**Comment by SijmenHuizenga** [comment]
Hi @Lu7913, It feels ages ago I did this :sweat_smile:. From a quick look I think the fbx file we used is `./Assets/ZZ_opendrive/FBX/Zalaegerszeg.fbx`.

**Comment by Lu7913** [comment]
Been looking for fbx file in folders, apparently not enough :disappointed_relieved:. Thanks.
